[enterprise]
domains = [
    ["alimail.com", "alibabamail"],
    ["basecamp.com", "hey"],
    ["google.com", "google workspace"],
    ["hey.com", "hey"],
    ["mxhichina.com", "alibabamail"],
    ["outlook.com", "outlook"],
    ["zoho.com", "zoho"]
]

[hosting]
domains = [
    ["aliyun.com", "alibaba cloud"],
    ["amazonaws.com", "amazon web services"],
    ["areait.lv", "area it"],
    ["bluehost.com", "bluehost"],
    ["deltablue.cloud", "delta blue"],
    ["dnssmarthost.net", "dns smart host"],
    ["dreamhost.com", "dreamhost"],
    ["emailsrvr.com", "rackspace"],
    ["franticllc.com", "franticllc.com"],
    ["greengeeks.net", "greengeeks"],
    ["hetzner.com", "hetzner"],
    ["hostedemail.com", "tucows"],
    ["hostinger.com", "hostinger"],
    ["infomaniak.com", "infomaniak"],
    ["intermedia.net", "intermedia"],
    ["ionos.com", "ionos"],
    ["kinstamailservice.com", "kinsta mail"],
    ["mail.com", "mail.com"],
    ["mailcow.email", "mailcow"],
    ["mailhostbox.com", "mailhostbox"],
    ["messagingengine.com", "fastmail"],
    ["migadu.com", "migadu"],
    ["mxrecord.io", "mx record"],
    ["ovh.com", "ovh"],
    ["pair.com", "pair networks"],
    ["pairlist.net", "pair list"],
    ["privateemail.com", "namecheap"],
    ["qlc.co.in", "quantumlink communications"],
    ["secureserver.net", "godaddy"],
    ["serverdata.net", "sherweb"],
    ["stackmail.com", "steadfast"],
    ["vas-hosting.cz", "vas hosting"],
    ["web-hosting.com", "web hosting"],
    ["websitewelcome.com", "website welcome"],
    ["zimbra.com", "zimbra"]
]

[webmail]
domains = [
    ["163.com", "netease"],
    ["263.net", "263"],
    ["263xmail.com", "263 xmail"],
    ["antispameurope.com", "hornetsecurity"],
    ["daum.net", "daum"],
    ["gmx.net", "gmx"],
    ["haihaimail.jp", "haihai mail"],
    ["hornetsecurity.com", "hornetsecurity"],
    ["hushmail.com", "hushmail"],
    ["icloud.com", "icloud"],
    ["mail.ru", "mailru"],
    ["mailbox.org", "mailbox.org"],
    ["mailfence.com", "mailfence"],
    ["naver.com", "naver"],
    ["ocmail.in", "oc mail"],
    ["outlook.com", "outlook"],
    ["posteo.de", "posteo"],
    ["protonmail.ch", "protonmail"],
    ["qq.com", "tencent"],
    ["runbox.com", "runbox"],
    ["sina.com", "sinamail"],
    ["sohu.com", "sohumail"],
    ["tutanota.de", "tutanota"],
    ["web.de", "webde"],
    ["yahoo.com", "yahoo"],
    ["yahoodns.net", "yahoo"],
    ["yandex.net", "yandex"],
    ["yandex.ru", "yandex"],
    ["zcsend.net", "zoho"],
    ["zoho.eu", "zoho eu"],
    ["zoho.in", "zoho india"]
]

[security]
domains = [
    ["agari.com", "agari"],
    ["antispam.mailspamprotection.com", "mail spam protection"],
    ["barracudanetworks.com", "barracuda"],
    ["edgepilot.com", "edge pilot"],
    ["egress.com", "egress"],
    ["encrypttitan.net", "encrypt titan"],
    ["forcepoint.com", "forcepoint"],
    ["greathorn.com", "greathorn"],
    ["iphmx.com", "cisco ironport"],
    ["mailcontrol.com", "mail control"],
    ["messagelabs.com", "broadcom"],
    ["mimecast.com", "mimecast"],
    ["mimecastprotect.com", "mimecast"],
    ["ondmarc.com", "ondmarc"],
    ["powerspf.com", "power spf"],
    ["pphosted.com", "proofpoint"],
    ["ppe-hosted.com", "proofpoint"],
    ["redpoints.com", "red points"],
    ["reflexion.net", "sophos"],
    ["res.cisco.com", "cisco"],
    ["simplyspamfree.com", "spamexperts"],
    ["skysnag.com", "skysnag"],
    ["sophos.com", "sophos"],
    ["spamexperts.com", "solarwinds"],
    ["tacklephishing.com", "tackle phishing"],
    ["trendmicro.com", "trendmicro"],
    ["worldsecuresystems.com", "world secure systems"],
    ["zixmail.net", "zix"]
]
