matches = [
  '123',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2022',
  '2023',
  '2024',
  'aaa',
  'abc',
  'adm',
  'ads',
  'all',
  'alla',
  'alle',
  'ap',
  'api',
  'app',
  'apps',
  'appstore',
  'apple',
  'arin',
  'asd',
  'ask',
  'asset',
  'avis',
  'bcc',
  'bd',
  'beta',
  'bod',
  'bot',
  'bills',
  'biz',
  'ca',
  'capital',
  'care',
  'ceo',
  'chat',
  'church',
  'clay',
  'cm',
  'com',
  'crm',
  'cs',
  'csm',
  'dandb',
  'dev',
  'dns',
  'eng',
  'enq',
  'fax',
  'fte',
  'ftp',
  'fun',
  'gm',
  'hatch',
  'heap',
  'hi',
  'hq',
  'hr',
  'ios',
  'infisical',
  'ir',
  'it',
  'job',
  'la',
  'lab',
  'labs',
  'lead',
  'learn',
  'learning',
  'lusha',
  'md',
  'mt',
  'no',
  'ny',
  'nps',
  'oratory',
  'pay',
  'pd',
  'per',
  'plain',
  'pm',
  'pr',
  'read',
  'reg',
  'rh',
  'rnd',
  'sac',
  'sale',
  'sales',
  'send',
  'ship',
  'signal',
  'se',
  'sem',
  'seo',
  'sf',
  'ta',
  'tax',
  'tips',
  'token',
  'uk',
  'us',
  'usa',
  'ux',
  'vip',
  'web'
]

contains = [
  'abuse',
  'academy',
  'access',
  'account',
  'acquisition',
  'admin',
  'admisiones',
  'admissions',
  'adobe',
  'adops',
  'adventure',
  'advertise',
  'advertising',
  'advice',
  'advisor',
  'adwords',
  'aetna',
  'affiliate',
  'africa',
  'agence',
  'agencia',
  'agency',
  'agents',
  'airbnb',
  'airbyte',
  'alarm',
  'alert',
  'all-',
  'all.',
  'all_',
  'allemployees',
  'allhands',
  'allsales',
  'allstaff',
  'allstudents',
  'allteachers',
  'allteam',
  'allusers',
  'alpha',
  'alumni',
  'ambassadors',
  'american',
  'amministrazione',
  'amazon',
  'analysts',
  'analytics',
  'android',
  'angels',
  'animation',
  'announce',
  'apple',
  'application',
  'apply',
  'appointments',
  'archives',
  'arin-abuse',
  'asdasd',
  'asdf',
  'asistente',
  'assistanthead',
  'assistencia',
  'assistenza',
  'associates',
  'ateam',
  'atencionalcliente',
  'atendimento',
  'auctions',
  'author',
  'auto-',
  'automation',
  'available',
  'awesome',
  'b2b',
  'backend',
  'backup',
  'balance',
  'banking',
  'benefits',
  'berlin',
  'bestellung',
  'biblioteca',
  'bibliotheque',
  'billing',
  'biuro',
  'bizdev',
  'blog',
  'board',
  'books',
  'bookclub',
  'bookkeeping',
  'booking',
  'boston',
  'bounce',
  'boxoffice',
  'brand',
  'broadcast',
  'broker',
  'buchhaltung',
  'budget',
  'bugs',
  'build',
  'bursar',
  'busdev',
  'business',
  'butik',
  'buyer',
  'caltrain',
  'campaign',
  'campusteam',
  'capacitacion',
  'capital',
  'capetown',
  'captain',
  'cards',
  'career',
  'catering',
  'celsius',
  'central',
  'centro',
  'ceos',
  'certific',
  'change',
  'channel',
  'chartering',
  'chatter',
  'chef',
  'chicago',
  'china',
  'citymanagers',
  'claim',
  'classof',
  'classroom',
  'clearbit',
  'client',
  'clinic',
  'cloud',
  'co-op',
  'coach',
  'code',
  'coin-',
  'cointracker',
  'colaboradores',
  'colegio',
  'collect',
  'comenzi',
  'comercial',
  'comment',
  'commercial',
  'commission',
  'committee',
  'comms',
  'communication',
  'community',
  'companies',
  'company',
  'compete',
  'competition',
  'complaints',
  'compliance',
  'compras',
  'compta',
  'comptabilite',
  'comunicacao',
  'comunicacion',
  'comunicazione',
  'concierge',
  'conference',
  'confidential',
  'connect',
  'consultant',
  'consultas',
  'consulting',
  'consultoria',
  'contabil',
  'contabilidad',
  'contabilidade',
  'contabilita',
  'contact',
  'contactenos',
  'contacto',
  'contador',
  'contato',
  'content',
  'contractor',
  'contracts',
  'controller',
  'coordinator',
  'copilot',
  'copyright',
  'core',
  'corp',
  'council',
  'courrier',
  'creative',
  'creditor',
  'crew',
  'csteam',
  'cultura',
  'culture',
  'customer',
  'custserv',
  'daemon',
  'data',
  'database',
  'deals',
  'delivery',
  'deltek',
  'demo',
  'denver',
  'departures',
  'deploy',
  'deputy',
  'deputyhead',
  'design',
  'dev.',
  'dev-',
  'dev_',
  'developer',
  'digest',
  'digital',
  'digsitesvalue',
  'direccion',
  'direction',
  'directo',
  'diretoria',
  'direzione',
  'discuss',
  'dispatch',
  'diversity',
  'dividend',
  'dmarc',
  'dns.',
  'dns-',
  'do-not',
  'docs',
  'documents',
  'domain',
  'donation',
  'donor',
  'donot',
  'download',
  'dreamteam',
  'ecommerce',
  'editor',
  'editorial',
  'editors',
  'education',
  'einkauf',
  'email',
  'email.campaign',
  'emergency',
  'employ',
  'eng-all',
  'engagement',
  'engenharia',
  'engineering',
  'engineers',
  'english',
  'enquire',
  'enquiries',
  'enquiry',
  'enrollment',
  'enterprise',
  'envio',
  'equipe',
  'equipo',
  'error',
  'escritorio',
  'europe',
  'event',
  'everybody',
  'everyone',
  'exec',
  'expense',
  'expert',
  'export',
  'facebook',
  'facilities',
  'facturacion',
  'faculty',
  'failed',
  'family',
  'farmacia',
  'faturamento',
  'fbl',
  'feedback',
  'fellows',
  'finance',
  'financeiro',
  'finanzas',
  'firmapost',
  'fiscal',
  'food',
  'football',
  'founder',
  'founding',
  'france',
  'franchise',
  'friend',
  'from',
  'frontdesk',
  'frontend',
  'frontoffice',
  'fulltime',
  'fundraising',
  'gardner',
  'geeks',
  'general',
  'geral',
  'gerencia',
  'ghsa',
  'gift',
  'gifts',
  'giving',
  'global',
  'grants',
  'graphics',
  'group',
  'growth',
  'hackathon',
  'hackers',
  'head',
  'health',
  'hello',
  'help',
  'highschool',
  'hiring',
  'hola',
  'home',
  'hosting',
  'hostmaster',
  'hotel',
  'house',
  'hr-',
  'hr.',
  'hsbc',
  'hsstaff',
  'hsteachers',
  'hubspot',
  'human_resources',
  'humanresources',
  'idea',
  'identity',
  'ifttt',
  'implementation',
  'import',
  'inbound',
  'inbox',
  'india',
  'info',
  'infra',
  'ingenieria',
  'innkeeper',
  'innovation',
  'inoc',
  'inquiries',
  'inquiry',
  'insidesales',
  'insight',
  'instagram',
  'insurance',
  'integration',
  'interest',
  'intern',
  'invest',
  'invite',
  'invoice',
  'invoicing',
  'iphone',
  'ispfeedback',
  'ispsupport',
  'ithelp',
  'itsupport',
  'itunes',
  'jira',
  'job.',
  'job-',
  'jobs',
  'join',
  'jornalismo',
  'junk',
  'kontakt',
  'kundeservice',
  'laboratorio',
  'ladies',
  'latam',
  'launch',
  'leasing',
  'legal',
  'letschat',
  'letter',
  'library',
  'licensing',
  'lifesum',
  'linkedin',
  'links',
  'list',
  'login',
  'logistica',
  'logistics',
  'logistiek',
  'lunch',
  'mail',
  'maintenance',
  'majordomo',
  'management',
  'manager',
  'marketing',
  'marketplace',
  'master',
  'mayor',
  'media',
  'meet',
  'member',
  'mentors',
  'merchant',
  'messenger',
  'metrics',
  'mgmt',
  'microsoft',
  'middleschool',
  'migration',
  'misc',
  'mkt',
  'mobile',
  'monitor',
  'montreal',
  'moreinfo',
  'msstaff',
  'msteachers',
  'music',
  'myplex',
  'namecheap',
  'network',
  'newbiz',
  'newbusiness',
  'news',
  'newyork',
  'nntp',
  'no-',
  'no.',
  'nobody',
  'noc',
  'noemail',
  'none',
  'noreply',
  'noreply-dmarc',
  'noresponse',
  'northamerica',
  'nospam',
  'notes',
  'notice',
  'notices',
  'notification',
  'notify',
  'null',
  'numbers',
  'nyoffice',
  'offboarding',
  'offerallert',
  'offers',
  'office',
  'offtopic',
  'oficina',
  'onboarding',
  'online',
  'onsite',
  'ooo',
  'openline',
  'opensource',
  'operaciones',
  'operations',
  'ops',
  'order',
  'ordini',
  'outage',
  'outlook',
  'outreach',
  'owners',
  'parents',
  'paris',
  'partner',
  'partnership',
  'part',
  'pastor',
  'payment',
  'people',
  'performance',
  'personnel',
  'phish',
  'phishing',
  'photos',
  'planning',
  'platform',
  'plex',
  'podcast',
  'portfolio',
  'post',
  'ppc',
  'prefeitura',
  'presales',
  'presidencia',
  'president',
  'press',
  'prime',
  'principa',
  'privacy',
  'private',
  'privatebanking',
  'procurement',
  'prod',
  'program',
  'project',
  'promo',
  'protocollo',
  'proveedores',
  'publicidade',
  'publisher',
  'pump',
  'purchase',
  'purchasing',
  'qa',
  'qualidade',
  'question',
  'quotes',
  'random',
  'realestate',
  'receipt',
  'recepcion',
  'reception',
  'reconciliation',
  'record',
  'recruit',
  'recrutement',
  'recursoshumanos',
  'redacao',
  'redaccion',
  'redaction',
  'redazione',
  'referrals',
  'register',
  'registra',
  'registration',
  'regulatory',
  'reklama',
  'relacionamento',
  'release',
  'remote',
  'remove',
  'renewal',
  'rentals',
  'replay',
  'report',
  'request',
  'research',
  'reserva',
  'reservaciones',
  'reservation',
  'residents',
  'response',
  'restaurant',
  'result',
  'resume',
  'retail',
  'retool',
  'returns',
  'revenue',
  'reward',
  'rezervari',
  'rfp',
  'rockstars',
  'root',
  'rrhh',
  'rsvp',
  'saas',
  'sales-',
  'sales.',
  'sales1',
  'sales2',
  'salesengineers',
  'salesforce',
  'salesops',
  'salesteam',
  'sanfrancisco',
  'scale',
  'school',
  'science',
  'script',
  'sdr',
  'search',
  'seattle',
  'secretaria',
  'secretaris',
  'secretary',
  'security',
  'sekretariat',
  'seniors',
  'server',
  'service',
  'servicioalcliente',
  'session',
  'shareholders',
  'ship',
  'shipping',
  'shop',
  'signup',
  'singapore',
  'sistemas',
  'site',
  'small.business',
  'smile',
  'smtp',
  'social',
  'socios',
  'software',
  'solutions',
  'soporte',
  'sos',
  'spam',
  'sponsorship',
  'sport',
  'squad',
  'staff',
  'startup',
  'statement',
  'stats',
  'stay',
  'stockholm',
  'stop',
  'store',
  'stories',
  'strategy',
  'stripe',
  'student',
  'studio',
  'submissions',
  'submit',
  'subscribe',
  'subscriptions',
  'success',
  'suggestions',
  'superintendent',
  'supervisor',
  'suporte',
  'supply',
  'support',
  'suprimentos',
  'summit',
  'survey',
  'sysadmin',
  'system',
  'talent',
  'teacher',
  'team',
  'tech',
  'tecnologia',
  'tesoreria',
  'test',
  'tickets',
  'time',
  'todos',
  'tools',
  'tour',
  'trade',
  'trainers',
  'training',
  'transcript',
  'transport',
  'travel',
  'treasurer',
  'tribe',
  'truck',
  'trustees',
  'turbotax',
  'turismo',
  'twitter',
  'undisclosed',
  'unsubscribe',
  'update',
  'usenet',
  'user',
  'usteam',
  'uucp',
  'vendas',
  'vendor',
  'ventas',
  'venture',
  'vercel',
  'verkauf',
  'verwaltung',
  'video',
  'view',
  'vistaprint',
  'voice',
  'volunteer',
  'vorstand',
  'warehouse',
  'watercooler',
  'webadmin',
  'webdesign',
  'webdev',
  'webinar',
  'webmaster',
  'website',
  'webteam',
  'welcome',
  'whois',
  'wholesale',
  'women',
  'wordpress',
  'work',
  'workshop',
  'writers',
  'www',
  'zakaz',
  'zentrale'
]
