package mx

var EmailProviders = map[string]string{
	"include:amazonses.com":              "amazon ses",
	"include:spf.protection.outlook.com": "outlook",
	"include:_spf.google.com":            "google",
	"include:_spf.hostedemail.com":       "tucows",
	"include:zoho.com":                   "zoho",
	"include:mailgun.org":                "mailgun",
	"include:sendgrid.net":               "sendgrid",
	"include:servers.mcsv.net":           "mailchimp",
	"include:spf.constantcontact.com":    "constant contact",
	"include:_spf.protonmail.ch":         "protonmail",
	"include:spf.messagingengine.com":    "fastmail",
	"include:spf.mail.yahoo.com":         "yahoo",
	"include:spf.mtasv.net":              "postmark",
	"include:spf.sendinblue.com":         "sendinblue",
	"include:cmail*.com":                 "campaign monitor",
	"include:spf.mailerlite.com":         "mailerlite",
	"include:hubspot.net":                "hubspot",
	"include:_spf.salesforce.com":        "salesforce",
	"include:spf.mandrillapp.com":        "mandrill",
	"include:sparkpostmail.com":          "sparkpost",
	"include:elasticemail.com":           "elasticemail",
	"include:spf.alimail.com":            "alibabamail",
	"include:spf.qq.com":                 "tencent",
	"include:spf.163.com":                "netease",
	"include:spf.sina.com":               "sinamail",
	"include:spf.sohu.com":               "sohumail",
	"include:_spf.mail.ru":               "mailru",
	"include:_spf.yandex.ru":             "yandex",
	"include:_spf.naver.com":             "naver",
	"include:spf.daum.net":               "daum",
	"include:spf.gmx.net":                "gmx",
	"include:spf.web.de":                 "webde",
	"include:spf.hushmail.com":           "hushmail",
	"include:spf.runbox.com":             "runbox",
	"include:pphosted.com":               "proofpoint",
	"include:_netblocks.mimecast.com":    "mimecast",
	"include:spf.barracudanetworks.com":  "barracuda",
	"include:spf.messagelabs.com":        "broadcom",
	"include:res.cisco.com":              "cisco",
	"include:spf.trendmicro.com":         "trendmicro",
	"include:spf.forcepoint.com":         "forcepoint",
	"include:spf.intermedia.net":         "intermedia",
	"include:emailsrvr.com":              "rackspace",
	"include:spf.zimbra.com":             "zimbra",
	"include:spf.reflexion.net":          "sophos",
	"include:smtp.secureserver.net":      "godaddy",
	"include:zixmail.net":                "zix",
	"include:spf.spamexperts.com":        "solarwinds",
	"include:spf.greathorn.com":          "greathorn",
	"include:spf.retarus.com":            "retarus",
	"include:spf.egress.com":             "egress",
	"include:spf.mxhichina.com":          "alibabamail",
	"include:mx.ovh.com":                 "ovh",
	"include:spf.hetzner.com":            "hetzner",
	"include:secureserver.net":           "godaddy",
	"include:spf.ionos.com":              "ionos",
	"include:spf.dreamhost.com":          "dreamhost",
	"include:spf.privateemail.com":       "namecheap",
	"include:spf.tutanota.de":            "tutanota",
	"include:spf.migadu.com":             "migadu",
	"include:icloud.com":                 "icloud",
	"include:us._netblocks.mimecast.com": "mimecast",
	"include:secondstreetmail.com":       "uplandsoftware",
}
